region = "us-east-1"
project = "aws15"
ami = "ami-0c02fb55956c7d316"
instance_type = "t3.micro"
db_user = "admin"
db_pass = "Password123!"
lambda_zip_path = "lambda.zip"
domain = "sathyapai.online"
